const fs = require('fs');
const path = require('path');

// Language translations (professional translations - note: these are examples, you should use professional translation service)
const translations = {
  'af-ZA': { name: 'Afrikaans', common: { header: { language: 'Taal' }, buttons: { getStarted: "Ek is gereed - Kom ons begin!", continue: 'Gaan voort', back: 'Terug', submit: 'Indien', cancel: 'Kanselleer', save: 'Stoor', logout: 'Teken uit' }, common: { welcome: 'Welkom', loading: 'Laai...', error: 'Fout', success: 'Sukses' } } },
  'sq-AL': { name: 'Albanian', common: { header: { language: 'Gjuha' }, buttons: { getStarted: "Jam gati - Le të fillojmë!", continue: 'Vazhdo', back: 'Prapa', submit: 'Dërgo', cancel: 'Anulo', save: 'Ruaj', logout: 'Dil' }, common: { welcome: 'Mirë se vini', loading: 'Duke ngarkuar...', error: 'Gabim', success: 'Sukses' } } },
  'ar': { name: 'Arabic', common: { header: { language: 'اللغة' }, buttons: { getStarted: "أنا جاهز - لنبدأ!", continue: 'متابعة', back: 'رجوع', submit: 'إرسال', cancel: 'إلغاء', save: 'حفظ', logout: 'تسجيل الخروج' }, common: { welcome: 'مرحباً', loading: 'جار التحميل...', error: 'خطأ', success: 'نجاح' } } },
  'ar-EG': { name: 'Arabic (Egypt)', common: { header: { language: 'اللغة' }, buttons: { getStarted: "أنا جاهز - يلا نبدأ!", continue: 'متابعة', back: 'رجوع', submit: 'إرسال', cancel: 'إلغاء', save: 'حفظ', logout: 'تسجيل الخروج' }, common: { welcome: 'أهلاً', loading: 'بيحمل...', error: 'خطأ', success: 'تمام' } } },
  'hy-AM': { name: 'Armenian', common: { header: { language: 'Լեզու' }, buttons: { getStarted: "Ես պատրաստ եմ - Եկեք սկսենք!", continue: 'Շարունակել', back: 'Հետ', submit: 'Ուղարկել', cancel: 'Չեղարկել', save: 'Պահպանել', logout: 'Դուրս գալ' }, common: { welcome: 'Բարի գալուստ', loading: 'Բեռնվում է...', error: 'Սխալ', success: 'Հաջողություն' } } },
  'bn-BD': { name: 'Bengali', common: { header: { language: 'ভাষা' }, buttons: { getStarted: "আমি প্রস্তুত - চলুন শুরু করি!", continue: 'চালিয়ে যান', back: 'পিছনে', submit: 'জমা দিন', cancel: 'বাতিল', save: 'সংরক্ষণ', logout: 'প্রস্থান' }, common: { welcome: 'স্বাগতম', loading: 'লোড হচ্ছে...', error: 'ত্রুটি', success: 'সফল' } } },
  'bg-BG': { name: 'Bulgarian', common: { header: { language: 'Език' }, buttons: { getStarted: "Готов съм - Да започваме!", continue: 'Продължи', back: 'Назад', submit: 'Изпрати', cancel: 'Отказ', save: 'Запази', logout: 'Изход' }, common: { welcome: 'Добре дошли', loading: 'Зареждане...', error: 'Грешка', success: 'Успех' } } },
  'ca-ES': { name: 'Catalan', common: { header: { language: 'Idioma' }, buttons: { getStarted: "Estic preparat - Comencem!", continue: 'Continuar', back: 'Enrere', submit: 'Enviar', cancel: 'Cancel·lar', save: 'Desar', logout: 'Sortir' }, common: { welcome: 'Benvingut', loading: 'Carregant...', error: 'Error', success: 'Èxit' } } },
  'hr-HR': { name: 'Croatian', common: { header: { language: 'Jezik' }, buttons: { getStarted: "Spreman sam - Krenimo!", continue: 'Nastavi', back: 'Natrag', submit: 'Pošalji', cancel: 'Otkaži', save: 'Spremi', logout: 'Odjava' }, common: { welcome: 'Dobrodošli', loading: 'Učitavanje...', error: 'Greška', success: 'Uspjeh' } } },
  'cs-CZ': { name: 'Czech', common: { header: { language: 'Jazyk' }, buttons: { getStarted: "Jsem připraven - Začněme!", continue: 'Pokračovat', back: 'Zpět', submit: 'Odeslat', cancel: 'Zrušit', save: 'Uložit', logout: 'Odhlásit se' }, common: { welcome: 'Vítejte', loading: 'Načítání...', error: 'Chyba', success: 'Úspěch' } } },
  'da-DK': { name: 'Danish', common: { header: { language: 'Sprog' }, buttons: { getStarted: "Jeg er klar - Lad os komme i gang!", continue: 'Fortsæt', back: 'Tilbage', submit: 'Indsend', cancel: 'Annuller', save: 'Gem', logout: 'Log ud' }, common: { welcome: 'Velkommen', loading: 'Indlæser...', error: 'Fejl', success: 'Succes' } } },
  'nl-NL': { name: 'Dutch', common: { header: { language: 'Taal' }, buttons: { getStarted: "Ik ben klaar - Laten we beginnen!", continue: 'Doorgaan', back: 'Terug', submit: 'Verzenden', cancel: 'Annuleren', save: 'Opslaan', logout: 'Uitloggen' }, common: { welcome: 'Welkom', loading: 'Laden...', error: 'Fout', success: 'Succes' } } },
  'et-EE': { name: 'Estonian', common: { header: { language: 'Keel' }, buttons: { getStarted: "Olen valmis - Alustame!", continue: 'Jätka', back: 'Tagasi', submit: 'Saada', cancel: 'Tühista', save: 'Salvesta', logout: 'Logi välja' }, common: { welcome: 'Tere tulemast', loading: 'Laadimine...', error: 'Viga', success: 'Edu' } } },
  'fi-FI': { name: 'Finnish', common: { header: { language: 'Kieli' }, buttons: { getStarted: "Olen valmis - Aloitetaan!", continue: 'Jatka', back: 'Takaisin', submit: 'Lähetä', cancel: 'Peruuta', save: 'Tallenna', logout: 'Kirjaudu ulos' }, common: { welcome: 'Tervetuloa', loading: 'Ladataan...', error: 'Virhe', success: 'Onnistui' } } },
  'fr-BE': { name: 'French (Belgium)', common: { header: { language: 'Langue' }, buttons: { getStarted: "Je suis prêt - Commençons!", continue: 'Continuer', back: 'Retour', submit: 'Soumettre', cancel: 'Annuler', save: 'Enregistrer', logout: 'Déconnexion' }, common: { welcome: 'Bienvenue', loading: 'Chargement...', error: 'Erreur', success: 'Succès' } } },
  'fr-CA': { name: 'French (Canada)', common: { header: { language: 'Langue' }, buttons: { getStarted: "Je suis prêt - Allons-y!", continue: 'Continuer', back: 'Retour', submit: 'Soumettre', cancel: 'Annuler', save: 'Sauvegarder', logout: 'Déconnexion' }, common: { welcome: 'Bienvenue', loading: 'Chargement...', error: 'Erreur', success: 'Succès' } } },
  'de-DE': { name: 'German', common: { header: { language: 'Sprache' }, buttons: { getStarted: "Ich bin bereit - Los geht's!", continue: 'Weiter', back: 'Zurück', submit: 'Senden', cancel: 'Abbrechen', save: 'Speichern', logout: 'Abmelden' }, common: { welcome: 'Willkommen', loading: 'Lädt...', error: 'Fehler', success: 'Erfolg' } } },
  'el-GR': { name: 'Greek', common: { header: { language: 'Γλώσσα' }, buttons: { getStarted: "Είμαι έτοιμος - Ας ξεκινήσουμε!", continue: 'Συνέχεια', back: 'Πίσω', submit: 'Υποβολή', cancel: 'Ακύρωση', save: 'Αποθήκευση', logout: 'Αποσύνδεση' }, common: { welcome: 'Καλώς ήρθατε', loading: 'Φόρτωση...', error: 'Σφάλμα', success: 'Επιτυχία' } } },
  'he-IL': { name: 'Hebrew', common: { header: { language: 'שפה' }, buttons: { getStarted: "אני מוכן - בואו נתחיל!", continue: 'המשך', back: 'חזור', submit: 'שלח', cancel: 'ביטול', save: 'שמור', logout: 'התנתק' }, common: { welcome: 'ברוך הבא', loading: 'טוען...', error: 'שגיאה', success: 'הצלחה' } } },
  'hi-IN': { name: 'Hindi', common: { header: { language: 'भाषा' }, buttons: { getStarted: "मैं तैयार हूं - चलो शुरू करें!", continue: 'जारी रखें', back: 'वापस', submit: 'भेजें', cancel: 'रद्द करें', save: 'सहेजें', logout: 'लॉग आउट' }, common: { welcome: 'स्वागत है', loading: 'लोड हो रहा है...', error: 'त्रुटि', success: 'सफलता' } } },
  'hu-HU': { name: 'Hungarian', common: { header: { language: 'Nyelv' }, buttons: { getStarted: "Készen állok - Kezdjük el!", continue: 'Tovább', back: 'Vissza', submit: 'Küldés', cancel: 'Mégse', save: 'Mentés', logout: 'Kijelentkezés' }, common: { welcome: 'Üdvözöljük', loading: 'Betöltés...', error: 'Hiba', success: 'Siker' } } },
  'id-ID': { name: 'Indonesian', common: { header: { language: 'Bahasa' }, buttons: { getStarted: "Saya siap - Mari kita mulai!", continue: 'Lanjutkan', back: 'Kembali', submit: 'Kirim', cancel: 'Batal', save: 'Simpan', logout: 'Keluar' }, common: { welcome: 'Selamat datang', loading: 'Memuat...', error: 'Kesalahan', success: 'Berhasil' } } },
  'it-IT': { name: 'Italian', common: { header: { language: 'Lingua' }, buttons: { getStarted: "Sono pronto - Iniziamo!", continue: 'Continua', back: 'Indietro', submit: 'Invia', cancel: 'Annulla', save: 'Salva', logout: 'Esci' }, common: { welcome: 'Benvenuto', loading: 'Caricamento...', error: 'Errore', success: 'Successo' } } },
  'ja-JP': { name: 'Japanese', common: { header: { language: '言語' }, buttons: { getStarted: "準備完了 - 始めましょう！", continue: '続ける', back: '戻る', submit: '送信', cancel: 'キャンセル', save: '保存', logout: 'ログアウト' }, common: { welcome: 'ようこそ', loading: '読み込み中...', error: 'エラー', success: '成功' } } },
  'ko-KR': { name: 'Korean', common: { header: { language: '언어' }, buttons: { getStarted: "준비됐어요 - 시작해요!", continue: '계속', back: '뒤로', submit: '제출', cancel: '취소', save: '저장', logout: '로그아웃' }, common: { welcome: '환영합니다', loading: '로딩 중...', error: '오류', success: '성공' } } },
  'lv-LV': { name: 'Latvian', common: { header: { language: 'Valoda' }, buttons: { getStarted: "Es esmu gatavs - Sāksim!", continue: 'Turpināt', back: 'Atpakaļ', submit: 'Iesniegt', cancel: 'Atcelt', save: 'Saglabāt', logout: 'Iziet' }, common: { welcome: 'Laipni lūdzam', loading: 'Ielādē...', error: 'Kļūda', success: 'Panākums' } } },
  'lt-LT': { name: 'Lithuanian', common: { header: { language: 'Kalba' }, buttons: { getStarted: "Aš pasirengęs - Pradėkime!", continue: 'Tęsti', back: 'Atgal', submit: 'Pateikti', cancel: 'Atšaukti', save: 'Išsaugoti', logout: 'Atsijungti' }, common: { welcome: 'Sveiki', loading: 'Kraunama...', error: 'Klaida', success: 'Sėkmė' } } },
  'mk-MK': { name: 'Macedonian', common: { header: { language: 'Јазик' }, buttons: { getStarted: "Подготвен сум - Да почнеме!", continue: 'Продолжи', back: 'Назад', submit: 'Испрати', cancel: 'Откажи', save: 'Зачувај', logout: 'Одјава' }, common: { welcome: 'Добредојдовте', loading: 'Вчитување...', error: 'Грешка', success: 'Успех' } } },
  'ms-MY': { name: 'Malaysian', common: { header: { language: 'Bahasa' }, buttons: { getStarted: "Saya bersedia - Mari kita mulakan!", continue: 'Teruskan', back: 'Kembali', submit: 'Hantar', cancel: 'Batal', save: 'Simpan', logout: 'Log keluar' }, common: { welcome: 'Selamat datang', loading: 'Memuatkan...', error: 'Ralat', success: 'Kejayaan' } } },
  'nb-NO': { name: 'Norwegian', common: { header: { language: 'Språk' }, buttons: { getStarted: "Jeg er klar - La oss begynne!", continue: 'Fortsett', back: 'Tilbake', submit: 'Send inn', cancel: 'Avbryt', save: 'Lagre', logout: 'Logg ut' }, common: { welcome: 'Velkommen', loading: 'Laster...', error: 'Feil', success: 'Suksess' } } },
  'pl-PL': { name: 'Polish', common: { header: { language: 'Język' }, buttons: { getStarted: "Jestem gotowy - Zaczynajmy!", continue: 'Kontynuuj', back: 'Wstecz', submit: 'Wyślij', cancel: 'Anuluj', save: 'Zapisz', logout: 'Wyloguj' }, common: { welcome: 'Witamy', loading: 'Ładowanie...', error: 'Błąd', success: 'Sukces' } } },
  'pt-BR': { name: 'Portuguese (Brazil)', common: { header: { language: 'Idioma' }, buttons: { getStarted: "Estou pronto - Vamos começar!", continue: 'Continuar', back: 'Voltar', submit: 'Enviar', cancel: 'Cancelar', save: 'Salvar', logout: 'Sair' }, common: { welcome: 'Bem-vindo', loading: 'Carregando...', error: 'Erro', success: 'Sucesso' } } },
  'pt-PT': { name: 'Portuguese (Portugal)', common: { header: { language: 'Idioma' }, buttons: { getStarted: "Estou pronto - Vamos começar!", continue: 'Continuar', back: 'Voltar', submit: 'Submeter', cancel: 'Cancelar', save: 'Guardar', logout: 'Terminar sessão' }, common: { welcome: 'Bem-vindo', loading: 'A carregar...', error: 'Erro', success: 'Sucesso' } } },
  'ro-RO': { name: 'Romanian', common: { header: { language: 'Limbă' }, buttons: { getStarted: "Sunt gata - Să începem!", continue: 'Continuă', back: 'Înapoi', submit: 'Trimite', cancel: 'Anulează', save: 'Salvează', logout: 'Deconectare' }, common: { welcome: 'Bun venit', loading: 'Se încarcă...', error: 'Eroare', success: 'Succes' } } },
  'ru-RU': { name: 'Russian', common: { header: { language: 'Язык' }, buttons: { getStarted: "Я готов - Начнём!", continue: 'Продолжить', back: 'Назад', submit: 'Отправить', cancel: 'Отмена', save: 'Сохранить', logout: 'Выйти' }, common: { welcome: 'Добро пожаловать', loading: 'Загрузка...', error: 'Ошибка', success: 'Успех' } } },
  'sr-RS': { name: 'Serbian', common: { header: { language: 'Језик' }, buttons: { getStarted: "Спреман сам - Почнимо!", continue: 'Настави', back: 'Назад', submit: 'Пошаљи', cancel: 'Откажи', save: 'Сачувај', logout: 'Одјава' }, common: { welcome: 'Добродошли', loading: 'Учитавање...', error: 'Грешка', success: 'Успех' } } },
  'zh-CN': { name: 'Simplified Chinese', common: { header: { language: '语言' }, buttons: { getStarted: "我准备好了 - 让我们开始吧！", continue: '继续', back: '返回', submit: '提交', cancel: '取消', save: '保存', logout: '登出' }, common: { welcome: '欢迎', loading: '加载中...', error: '错误', success: '成功' } } },
  'sk-SK': { name: 'Slovak', common: { header: { language: 'Jazyk' }, buttons: { getStarted: "Som pripravený - Začnime!", continue: 'Pokračovať', back: 'Späť', submit: 'Odoslať', cancel: 'Zrušiť', save: 'Uložiť', logout: 'Odhlásiť sa' }, common: { welcome: 'Vitajte', loading: 'Načítava sa...', error: 'Chyba', success: 'Úspech' } } },
  'sl-SI': { name: 'Slovenian', common: { header: { language: 'Jezik' }, buttons: { getStarted: "Pripravljen sem - Začnimo!", continue: 'Nadaljuj', back: 'Nazaj', submit: 'Pošlji', cancel: 'Prekliči', save: 'Shrani', logout: 'Odjava' }, common: { welcome: 'Dobrodošli', loading: 'Nalaganje...', error: 'Napaka', success: 'Uspeh' } } },
  'es-AR': { name: 'Spanish (Argentina)', common: { header: { language: 'Idioma' }, buttons: { getStarted: "Estoy listo - ¡Empecemos!", continue: 'Continuar', back: 'Atrás', submit: 'Enviar', cancel: 'Cancelar', save: 'Guardar', logout: 'Cerrar sesión' }, common: { welcome: 'Bienvenido', loading: 'Cargando...', error: 'Error', success: 'Éxito' } } },
  'es-MX': { name: 'Spanish (Mexico)', common: { header: { language: 'Idioma' }, buttons: { getStarted: "Estoy listo - ¡Comencemos!", continue: 'Continuar', back: 'Atrás', submit: 'Enviar', cancel: 'Cancelar', save: 'Guardar', logout: 'Cerrar sesión' }, common: { welcome: 'Bienvenido', loading: 'Cargando...', error: 'Error', success: 'Éxito' } } },
  'sv-SE': { name: 'Swedish', common: { header: { language: 'Språk' }, buttons: { getStarted: "Jag är redo - Låt oss börja!", continue: 'Fortsätt', back: 'Tillbaka', submit: 'Skicka', cancel: 'Avbryt', save: 'Spara', logout: 'Logga ut' }, common: { welcome: 'Välkommen', loading: 'Laddar...', error: 'Fel', success: 'Framgång' } } },
  'th-TH': { name: 'Thai', common: { header: { language: 'ภาษา' }, buttons: { getStarted: "ฉันพร้อมแล้ว - มาเริ่มกันเลย!", continue: 'ดำเนินการต่อ', back: 'ย้อนกลับ', submit: 'ส่ง', cancel: 'ยกเลิก', save: 'บันทึก', logout: 'ออกจากระบบ' }, common: { welcome: 'ยินดีต้อนรับ', loading: 'กำลังโหลด...', error: 'ข้อผิดพลาด', success: 'สำเร็จ' } } },
  'zh-TW': { name: 'Traditional Chinese (Taiwan)', common: { header: { language: '語言' }, buttons: { getStarted: "我準備好了 - 讓我們開始吧！", continue: '繼續', back: '返回', submit: '提交', cancel: '取消', save: '保存', logout: '登出' }, common: { welcome: '歡迎', loading: '載入中...', error: '錯誤', success: '成功' } } },
  'tr-TR': { name: 'Turkish', common: { header: { language: 'Dil' }, buttons: { getStarted: "Hazırım - Başlayalım!", continue: 'Devam', back: 'Geri', submit: 'Gönder', cancel: 'İptal', save: 'Kaydet', logout: 'Çıkış' }, common: { welcome: 'Hoş geldiniz', loading: 'Yükleniyor...', error: 'Hata', success: 'Başarılı' } } },
  'uk-UA': { name: 'Ukrainian', common: { header: { language: 'Мова' }, buttons: { getStarted: "Я готовий - Почнемо!", continue: 'Продовжити', back: 'Назад', submit: 'Надіслати', cancel: 'Скасувати', save: 'Зберегти', logout: 'Вийти' }, common: { welcome: 'Ласкаво просимо', loading: 'Завантаження...', error: 'Помилка', success: 'Успіх' } } },
  'vi-VN': { name: 'Vietnamese', common: { header: { language: 'Ngôn ngữ' }, buttons: { getStarted: "Tôi đã sẵn sàng - Bắt đầu thôi!", continue: 'Tiếp tục', back: 'Quay lại', submit: 'Gửi', cancel: 'Hủy', save: 'Lưu', logout: 'Đăng xuất' }, common: { welcome: 'Chào mừng', loading: 'Đang tải...', error: 'Lỗi', success: 'Thành công' } } },
};

const localesDir = path.join(__dirname, 'public', 'locales');

// Create directories and files
Object.entries(translations).forEach(([langCode, data]) => {
  const langDir = path.join(localesDir, langCode);
  
  // Create directory
  if (!fs.existsSync(langDir)) {
    fs.mkdirSync(langDir, { recursive: true });
  }
  
  // Write common.json
  fs.writeFileSync(
    path.join(langDir, 'common.json'),
    JSON.stringify(data.common, null, 2)
  );
  
  console.log(`✅ Created translations for ${data.name} (${langCode})`);
});

console.log('\n🎉 All translation files created successfully!');
